import type { Metadata } from "next";
import "./globals.css";

import { TanStackProvider } from "@/providers/TanStackProvider";
// import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
   title: "HID App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body>
            <TanStackProvider>{children}</TanStackProvider>
         </body>
      </html>
   )
}
